### ISSUE TITLE
Versions of walkmod-cmd and walkmod-core are not synchronized

### ISSUE THREAD

**Issue by kstarsinic** [walkmod/walkmod-cmd#3]
When I run "walkmod --version" from walkmod-2.3.4 tarball:

```
version 2.3.0 - February 2016 -
--------------------------------------------------------------------------------
Walkmod version "2.3.0"
```

That text, of course, comes from walkmod-core. The version numbers for (at least) walkmod-cmd, walkmod-core, and walkmod-cfg seem to be racing each other in a way that I don't quite understand.

**Comment by rpau** [comment]
Sorry for the delayed response. Incorrect github notification settings made me ignore it. Thanks for reporting it anyway. With the new version this is not an issue anymore.
